language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "6.1"

deploy:
  provider: npm
  email: "igor.bezkrovny@gmail.com"
  api_key: "8701189c-d219-40fc-ae6c-51cbd53eef18"

after_success:
  - npm run coveralls